

> **Data Cleaning & Preprocessing Tasks - Automobile dataset**



> **1) Handling Missing Values**

> **2) String & Categorical Data Preprocessing**

> **3) Numeric Feature Processing**


> **4) Feature Engineering on Numeric Columns**


> **5) Handling Date or Range Values**

> **6) Encoding Categorical Features**


> **7) Data Scaling & Normalization**

In [3]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
auto = pd.read_csv('Automobile (1).csv')
auto

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [5]:
auto.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [7]:
missing_values = auto[['normalized_losses', 'bore', 'stroke', 'horsepower', 'peak_rpm', 'price']].isnull().sum()
missing_values

normalized_losses    0
bore                 0
stroke               0
horsepower           0
peak_rpm             0
price                0
dtype: int64

In [8]:
auto['horsepower'].fillna(auto['horsepower'].mean(), inplace=True)
auto['price'].fillna(auto['price'].mean(), inplace=True)
auto.dropna(thresh=int(0.7*auto.shape[1]), inplace=True)

print(auto.isnull().sum())

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

<ipython-input-8-fe3ffe71efd7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['horsepower'].fillna(auto['horsepower'].mean(), inplace=True)
<ipython-input-8-fe3ffe71efd7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['price'].fillna(auto['price'].mean(), inplace=True)

In [9]:
auto

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
197,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
198,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
199,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [10]:
def clean_column_data(column):
    # Convert to lowercase and remove special characters using regex
    return column.str.lower().replace(r'[^a-z0-9\s]', '', regex=True)

# Clean specified categorical columns
auto['make'] = clean_column_data(auto['make'])
auto['fuel_type'] = clean_column_data(auto['fuel_type'])
auto['aspiration'] = clean_column_data(auto['aspiration'])
auto['body_style'] = clean_column_data(auto['body_style'])
auto['drive_wheels'] = clean_column_data(auto['drive_wheels'])
auto['engine_location'] = clean_column_data(auto['engine_location'])

# Verify changes
print(auto[['make', 'fuel_type', 'aspiration', 'body_style', 'drive_wheels', 'engine_location']].head())

         make fuel_type aspiration   body_style drive_wheels engine_location
0  alfaromero       gas        std  convertible          rwd           front
1  alfaromero       gas        std  convertible          rwd           front
2  alfaromero       gas        std    hatchback          rwd           front
3        audi       gas        std        sedan          fwd           front
4        audi       gas        std        sedan          4wd           front

In [11]:
# Replace '?' with NaN
auto.replace('?', np.nan, inplace=True)

# Fill NaN values in numerical columns with the median or mean
auto['horsepower'].fillna(auto['horsepower'].median(), inplace=True)
auto['price'].fillna(auto['price'].mean(), inplace=True)

# Fill NaN values in categorical columns with the mode
auto['number_of_doors'].fillna(auto['number_of_doors'].mode()[0], inplace=True)
auto['fuel_type'].fillna(auto['fuel_type'].mode()[0], inplace=True)

# Verify changes
print(auto.isnull().sum())

symboling              0
normalized_losses      0
make                   0
fuel_type              0
aspiration             0
number_of_doors        0
body_style             0
drive_wheels           0
engine_location        0
wheel_base             0
length                 0
width                  0
height                 0
curb_weight            0
engine_type            0
number_of_cylinders    0
engine_size            0
fuel_system            0
bore                   0
stroke                 0
compression_ratio      0
horsepower             0
peak_rpm               0
city_mpg               0
highway_mpg            0
price                  0
dtype: int64

<ipython-input-11-83938517d399>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['horsepower'].fillna(auto['horsepower'].median(), inplace=True)
<ipython-input-11-83938517d399>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['price'].fillna(auto['price'].mean(), inplace=True)
<ipython-input-11-83938517d399>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['number_of_doors'].fillna(auto['number_of_doors'].mode()[0], inplace=True)
<ipython-input-11-83938517d399>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto['fuel_type'].fillna(auto['fuel_type'].mode()[0], inplace=True)

In [12]:
# Standardize number_of_cylinders
auto['number_of_cylinders'] = auto['number_of_cylinders'].replace({
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8,
    'nine': 9,
    'ten': 10,
    'eleven': 11,
    'twelve': 12
})

# Standardize fuel_system categories
auto['fuel_system'] = auto['fuel_system'].replace({
    'mfi': 'Multi-Point Fuel Injection',
    'spfi': 'Single-Point Fuel Injection',
    'mpfi': 'Multi-Point Fuel Injection',
    '4bbl': 'Four-Barrel',
    'two-barrel': 'Two-Barrel',
    'one-barrel': 'One-Barrel',
    'idi': 'Indirect Injection',
    'single-point fuel injection': 'Single-Point Fuel Injection',
    'multi-point fuel injection': 'Multi-Point Fuel Injection',
})

# Verify the changes
print(auto[['number_of_cylinders', 'fuel_system']].head(50))

    number_of_cylinders                  fuel_system
0                     4   Multi-Point Fuel Injection
1                     4   Multi-Point Fuel Injection
2                     6   Multi-Point Fuel Injection
3                     4   Multi-Point Fuel Injection
4                     5   Multi-Point Fuel Injection
5                     5   Multi-Point Fuel Injection
6                     5   Multi-Point Fuel Injection
7                     5   Multi-Point Fuel Injection
8                     5   Multi-Point Fuel Injection
9                     4   Multi-Point Fuel Injection
10                    4   Multi-Point Fuel Injection
11                    6   Multi-Point Fuel Injection
12                    6   Multi-Point Fuel Injection
13                    6   Multi-Point Fuel Injection
14                    6   Multi-Point Fuel Injection
15                    6   Multi-Point Fuel Injection
16                    6   Multi-Point Fuel Injection
17                    3                         2bbl
18                    4                         2bbl
19                    4                         2bbl
20                    4                         2bbl
21                    4                         2bbl
22                    4   Multi-Point Fuel Injection
23                    4                         2bbl
24                    4                         2bbl
25                    4                         2bbl
26                    4   Multi-Point Fuel Injection
27                    4                         2bbl
28                    4   Multi-Point Fuel Injection
29                    4                         1bbl
30                    4                         1bbl
31                    4                         1bbl
32                    4                         1bbl
33                    4                         1bbl
34                    4                         1bbl
35                    4                         1bbl
36                    4                         1bbl
37                    4                         1bbl
38                    4                         1bbl
39                    4                         1bbl
40                    4   Multi-Point Fuel Injection
41                    4                         2bbl
42                    4                         2bbl
43                    4  Single-Point Fuel Injection
44                    6   Multi-Point Fuel Injection
45                    6   Multi-Point Fuel Injection
46                   12   Multi-Point Fuel Injection
47                    4                         2bbl
48                    4                         2bbl
49                    4                         2bbl

<ipython-input-12-7a5fc271a399>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  auto['number_of_cylinders'] = auto['number_of_cylinders'].replace({

In [13]:
auto['number_of_cylinders'].unique()

array([ 4,  6,  5,  3, 12,  2,  8])

In [14]:
auto['fuel_system'].unique()

array(['Multi-Point Fuel Injection', '2bbl', '1bbl',
       'Single-Point Fuel Injection', 'Four-Barrel', 'Indirect Injection',
       'spdi'], dtype=object)

In [15]:

auto['horsepower'].dtype
auto['peak_rpm'].dtype

dtype('int64')

In [16]:
auto['power_to_weight'] = auto['horsepower'] / auto['curb_weight']
auto[['power_to_weight']]

     power_to_weight
0           0.043564
1           0.043564
2           0.054552
3           0.043646
4           0.040722
..               ...
196         0.038618
197         0.052476
198         0.044489
199         0.032950
200         0.037231

[201 rows x 1 columns]

In [17]:
auto['engine_efficiency'] = auto['horsepower'] / auto['engine_size']
print(auto[ 'engine_efficiency'])

0      0.853846
1      0.853846
2      1.013158
3      0.935780
4      0.845588
         ...
196    0.808511
197    1.134752
198    0.774566
199    0.731034
200    0.808511
Name: engine_efficiency, Length: 201, dtype: float64

In [18]:
auto['fuel_efficiency'] = auto['city_mpg'] / auto['highway_mpg']
print(auto[  'fuel_efficiency'])

0      0.777778
1      0.777778
2      0.730769
3      0.800000
4      0.818182
         ...
196    0.821429
197    0.760000
198    0.782609
199    0.962963
200    0.760000
Name: fuel_efficiency, Length: 201, dtype: float64

In [19]:
auto.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price', 'power_to_weight', 'engine_efficiency',
       'fuel_efficiency'],
      dtype='object')

In [20]:
auto['compression_ratio']

0       9.0
1       9.0
2       9.0
3      10.0
4       8.0
       ...
196     9.5
197     8.7
198     8.8
199    23.0
200     9.5
Name: compression_ratio, Length: 201, dtype: float64

In [21]:
auto['compression_ratio_category'] = pd.cut(auto['compression_ratio'],
                                            bins=[-np.inf, 9, 11, np.inf],
                                            labels=['Low', 'Medium', 'High'])

print(auto[['compression_ratio', 'compression_ratio_category']].head())

   compression_ratio compression_ratio_category
0                9.0                        Low
1                9.0                        Low
2                9.0                        Low
3               10.0                     Medium
4                8.0                        Low

In [22]:
auto['normalized_losses'].head(50)

0     168
1     168
2     168
3     164
4     164
5     161
6     158
7     168
8     158
9     192
10    192
11    188
12    188
13    149
14    149
15    149
16    149
17    121
18     98
19     81
20    118
21    118
22    118
23    148
24    148
25    148
26    148
27    110
28    145
29    137
30    137
31    101
32    101
33    101
34    110
35     78
36    106
37    106
38     85
39     85
40     85
41    107
42    110
43    110
44    145
45    115
46    115
47    104
48    104
49    104
Name: normalized_losses, dtype: int64

In [23]:
auto['normalized_losses_category'] = pd.cut(auto['normalized_losses'],
                                             bins=[-np.inf, 100, 200, np.inf],
                                             labels=['Low', 'Medium', 'High'])

print(auto[['normalized_losses', 'normalized_losses_category']].head(50))

    normalized_losses normalized_losses_category
0                 168                     Medium
1                 168                     Medium
2                 168                     Medium
3                 164                     Medium
4                 164                     Medium
5                 161                     Medium
6                 158                     Medium
7                 168                     Medium
8                 158                     Medium
9                 192                     Medium
10                192                     Medium
11                188                     Medium
12                188                     Medium
13                149                     Medium
14                149                     Medium
15                149                     Medium
16                149                     Medium
17                121                     Medium
18                 98                        Low
19                 81                        Low
20                118                     Medium
21                118                     Medium
22                118                     Medium
23                148                     Medium
24                148                     Medium
25                148                     Medium
26                148                     Medium
27                110                     Medium
28                145                     Medium
29                137                     Medium
30                137                     Medium
31                101                     Medium
32                101                     Medium
33                101                     Medium
34                110                     Medium
35                 78                        Low
36                106                     Medium
37                106                     Medium
38                 85                        Low
39                 85                        Low
40                 85                        Low
41                107                     Medium
42                110                     Medium
43                110                     Medium
44                145                     Medium
45                115                     Medium
46                115                     Medium
47                104                     Medium
48                104                     Medium
49                104                     Medium

In [24]:
auto.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price', 'power_to_weight', 'engine_efficiency',
       'fuel_efficiency', 'compression_ratio_category',
       'normalized_losses_category'],
      dtype='object')

In [25]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   symboling                   201 non-null    int64
 1   normalized_losses           201 non-null    int64
 2   make                        201 non-null    object
 3   fuel_type                   201 non-null    object
 4   aspiration                  201 non-null    object
 5   number_of_doors             201 non-null    object
 6   body_style                  201 non-null    object
 7   drive_wheels                201 non-null    object
 8   engine_location             201 non-null    object
 9   wheel_base                  201 non-null    float64
 10  length                      201 non-null    float64
 11  width                       201 non-null    float64
 12  height                      201 non-null    float64
 13  curb_weight                 201 non-null    int64
 14  engine_type                 201 non-null    object
 15  number_of_cylinders         201 non-null    int64
 16  engine_size                 201 non-null    int64
 17  fuel_system                 201 non-null    object
 18  bore                        201 non-null    float64
 19  stroke                      201 non-null    float64
 20  compression_ratio           201 non-null    float64
 21  horsepower                  201 non-null    int64
 22  peak_rpm                    201 non-null    int64
 23  city_mpg                    201 non-null    int64
 24  highway_mpg                 201 non-null    int64
 25  price                       201 non-null    int64
 26  power_to_weight             201 non-null    float64
 27  engine_efficiency           201 non-null    float64
 28  fuel_efficiency             201 non-null    float64
 29  compression_ratio_category  201 non-null    category
 30  normalized_losses_category  201 non-null    category
dtypes: category(2), float64(10), int64(10), object(9)
memory usage: 46.3+ KB

In [26]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

categorical_columns = ['fuel_type', 'aspiration', 'drive_wheels']

for col in categorical_columns:
    auto[col] = label_encoder.fit_transform(auto[col])

print(auto[categorical_columns].head())

   fuel_type  aspiration  drive_wheels
0          1           0             2
1          1           0             2
2          1           0             2
3          1           0             1
4          1           0             0

In [27]:
auto = pd.get_dummies(auto, columns=['body_style', 'engine_type', 'fuel_system'], drop_first=True)
print(auto.head())

   symboling  normalized_losses        make  fuel_type  aspiration  \
0          3                168  alfaromero          1           0
1          3                168  alfaromero          1           0
2          1                168  alfaromero          1           0
3          2                164        audi          1           0
4          2                164        audi          1           0

  number_of_doors  drive_wheels engine_location  wheel_base  length  ...  \
0             two             2           front        88.6   168.8  ...
1             two             2           front        88.6   168.8  ...
2             two             2           front        94.5   171.2  ...
3            four             1           front        99.8   176.6  ...
4            four             0           front        99.4   176.6  ...

   engine_type_ohc  engine_type_ohcf  engine_type_ohcv  engine_type_rotor  \
0            False             False             False              False
1            False             False             False              False
2            False             False              True              False
3             True             False             False              False
4             True             False             False              False

   fuel_system_2bbl  fuel_system_Four-Barrel  fuel_system_Indirect Injection  \
0             False                    False                           False
1             False                    False                           False
2             False                    False                           False
3             False                    False                           False
4             False                    False                           False

   fuel_system_Multi-Point Fuel Injection  \
0                                    True
1                                    True
2                                    True
3                                    True
4                                    True

   fuel_system_Single-Point Fuel Injection  fuel_system_spdi
0                                    False             False
1                                    False             False
2                                    False             False
3                                    False             False
4                                    False             False

[5 rows x 43 columns]

In [28]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
auto[['length', 'width', 'height', 'curb_weight', 'engine_size']] = scaler.fit_transform(
    auto[['length', 'width', 'height', 'curb_weight', 'engine_size']]
)
print(auto[['length', 'width', 'height', 'curb_weight', 'engine_size']].head())

     length     width    height  curb_weight  engine_size
0 -0.439409 -0.853460 -2.034081    -0.014858     0.075389
1 -0.439409 -0.853460 -2.034081    -0.014858     0.075389
2 -0.244152 -0.185597 -0.559713     0.518080     0.606234
3  0.195176  0.148335  0.218425    -0.423766    -0.431327
4  0.195176  0.243744  0.218425     0.520017     0.220165

In [29]:
auto.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'drive_wheels', 'engine_location', 'wheel_base',
       'length', 'width', 'height', 'curb_weight', 'number_of_cylinders',
       'engine_size', 'bore', 'stroke', 'compression_ratio', 'horsepower',
       'peak_rpm', 'city_mpg', 'highway_mpg', 'price', 'power_to_weight',
       'engine_efficiency', 'fuel_efficiency', 'compression_ratio_category',
       'normalized_losses_category', 'body_style_hardtop',
       'body_style_hatchback', 'body_style_sedan', 'body_style_wagon',
       'engine_type_l', 'engine_type_ohc', 'engine_type_ohcf',
       'engine_type_ohcv', 'engine_type_rotor', 'fuel_system_2bbl',
       'fuel_system_Four-Barrel', 'fuel_system_Indirect Injection',
       'fuel_system_Multi-Point Fuel Injection',
       'fuel_system_Single-Point Fuel Injection', 'fuel_system_spdi'],
      dtype='object')